import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import "react-vertical-timeline-component/style.min.css";
import { Toaster } from "sonner";
import ContextProviders from "@/hooks/context";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Artify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{
          background:
            "linear-gradient(135.04deg, #FFF8F3 24.36%, #FFE3E3 75.64%)",
        }}
        className={`${poppins.className}  antialiased`}
      >
        <ContextProviders>{children}</ContextProviders>
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
